### ISSUE TITLE
Milestone 1 - Feedback

### ISSUE THREAD

**Issue by danielramandi** [UBC-MDS/energy_efficiency_analysis#77]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. 

**1. Project set-up**

- [x] The analysis notebook (*.ipynb or .Rmd) should be in a sub-directory called something sensible, such as analysis, src, notebooks, docs, etc, to aid in the discoverability of this file, and related ones. -1

**Comment:** I could not find the EDA report in the directory mentioned in the README. I was able to find it on the version zip file. I do not think it is necessary to remove the reports, as they are an important part of your project. 

**2. Code of Conduct.md** 

- [x] A procedure for reporting and dealing with unacceptable behavior is explicitly included. In particular, is important to add who to contact in case something happens. -2

**Comment:** This is an important section and I highly suggest adding it to your CofC.

**3. CONTRIBUTING.md**

- [x] #130

**Comment:** The contributing file could use some more explanation and details on how developers and users can participate in the project. Some parts are very short and unclear. It is important to clarify these policies and provide enough details to minimize the chance of confusion and issues later.

**4. Project proposal**

- [x] The project should be asking a predictive or statistical question. See [here](https://datasciencebook.ca/intro.html#asking-a-question) and [here](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/materials/lectures/01-intro-to-ds-workflows.html#revisiting-the-definition-of-data-science-what-is-the-question) for clarification if needed. -3 reasoning

- [ ] The question should be specific enough. For example, "Is eating a healthier diet better for you?" is written ambiguously. What do you mean by "healthier diet"? Instead, "Does eating at least 5 servings per day of fresh fruits and vegetables lead to fewer upper respiratory tract infections (colds)?" is clearer and more concrete. -1 reasoning

**Comment:** The question is very unclear, and is buried in the intro of the dataset. It is important to be clear and specific. Add a paragraph, clearly state the question (number them if there are multiple), and give any necessary details in another paragraph. Bold the question if necessary. It is very crucial to understand the question, before moving to the EDA and methodology, as otherwise, it would be impossible to follow the project information flow.

- [x] The clarity of README could be improved through additional proofreading (i.e., spelling and grammatical errors are present). -1

- [x] The proposed methodology in the README should be clearly explained, mentioning the statistical methods/models they will use (at least at a high level). -3 reasoning

**Comment:** I suggest adding some details on the methodology and proposed algorithms you would be using. Supervised learning is not detailed enough. Provide more details and a few sentences justifying the choices. (e.g. Ridge or other GLMs given high/low correlation of the features, collinearity, etc.)

**5. Exploratory data analysis in a literate code document**

- [x] Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text, or no axis labels. -2 viz

**Comment:** The histograms are hard to read. This is due to the scaling of the x-axis. I suggest trying to widen the bars by modifying the bins.

- [x] There are no figure captions. -2 viz

- [x] The captions for the tables should be above the table. -1 viz

**Comment:** Providing titles, captions, figure/table numbers, etc. makes it easier to refer to them in the text. It also helps in understanding and following the flow of the report. 

- [x] The text is difficult to understand. Clarity could be improved. There are many typos, the text is difficult to read. -2 writing

**Comment:** The clarity of the project can be influenced by the quality of the writing. Inconsistent tone, grammatical inaccuracies, and spelling errors can disengage the reader. I suggest keeping a semi-formal or neutral tone (avoid contractions, etc.), and proofreading. You can use Grammarly as a tool to check your writing.

**6. Expectations**

- [x] GitHub issues were not used. -5

**Comment:** Given that GitHub issues are the best way to communicate and document the progress of the project, report the problems of the code, etc. I highly suggest that you start using them.

**Overall comment:** The project is well designed and the dataset is chosen wisely to fit the project. However, the question is not clear. In order to improve and clarify the codes, scripts, reports, and documentation, more effort should be put into the proofreading process. I suggest having clear modules and sections in your reports and keeping a flow of the pipeline so that it is easy to follow and understand. Oversectioning the report also should be avoided. I suggest designing a frame for your report and building it up. eg. Intro, Data, Cleaning, EDA, etc.). In this example, EDA would have subsections for feature value distributions and feature correlations.

**Comment by YHuUBC** [comment]
Hi! Thank you for your detailed feedback on our Milestone 1. We appreciate your feedback but also have some confusion. Could you please kindly take a look at the responses below?

**Q1. Project set-up**
**Comment**: 
The analysis notebook (*.ipynb or .Rmd) should be in a sub-directory called something sensible, such as analysis, src, notebooks, docs, etc, to aid in the discoverability of this file, and related ones. -1

I could not find the EDA report in the directory mentioned in the README. I was able to find it on the version zip file. I do not think it is necessary to remove the reports, as they are an important part of your project.

**Response**: Thank you for your suggestion, and we agree with you. First, we indeed put the eda file in the src folder (as you suggested) in our v0.0.1 release (energy_efficiency_analysis-0.0.1.zip\energy_efficiency_analysis-0.0.1\src\energy_efficiency_eda.ipynb).

Also, while you were grading our Milestone 1, we were in the middle of moving the eda.ipynb file to a different folder with an even more sensible name (now it is in results/eda/energy_efficiency_eda.ipynb), and we were working on updating the link in the readme file. That was likely the reason you could not find the EDA report. We appreciate your valuable feedback, but we feel that was just an unfortunate coincidence of timing. Could you please consider removing the deduction for this point?

**Q3. CONTRIBUTING.md**
**Comment**: Contributing documentation should reflect all the ways people can contribute to the project (core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). -2

**Response**: Thank you for your comment. After reading your comment, we realized your suggestion is a good, detailed practice for writing a ‘contributing. Md’. However, in Milestone 1’s instructions, we were not told to do so. It simply says we could use the following as a template:
“We welcome all contributions to this project! If you notice a bug, or have a feature request, please open up an issue here. If you’d like to contribute a feature or bug fix, you can fork our repo and submit a pull request. We will review pull requests within 7 days. All contributors must abide by our code of conduct.”
**Cited from**: (https://pages.github.ubc.ca/MDS-2022-23/DSCI_522_dsci-workflows_students/materials/assignments/milestone1.html)

The template project's 'contributing.md' file is quite succinct, too (https://github.com/ttimbers/breast_cancer_predictor/blob/master/CONTRIBUTING.md)

**Q5. Exploratory data analysis in a literate code document**
**Comment**: Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text, or no axis labels. -2 viz
There are no figure captions. -2 viz

**Response**: We appreciate your feedback on the visualization. However, the instruction for Milestone 1 did not mention the specific expectations of the plots (e.g., overplotting). In DSCI 531, we learned that EDA plots are for researchers themselves to see and use rather than communicating with others; thus, the plotting details are not that important. Based on such reasoning, we created all the plots we needed. And we have figure captions and axis labels inside the plots. Could you please reconsider the points deduction here?

Also, we consider Milestone 1 as the starting point of our project; it is natural and logical to have things changed and improved later in the project. Based on your comments, we have and will continue to improve our project significantly.

Thank you.

**Comment by Suraporn** [comment]
Hello Daniel @danielramandi ,

Thank you for your feedback for milestone#1, but we do have some concerns about it as below.

4. Project proposal

Q4.1 
- The project should be asking a predictive or statistical question. See [here](https://datasciencebook.ca/intro.html#asking-a-question) and [here](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/materials/lectures/01-intro-to-ds-workflows.html#revisiting-the-definition-of-data-science-what-is-the-question) for clarification if needed. -3 reasoning
- The question should be specific enough. For example, "Is eating a healthier diet better for you?" is written ambiguously. What do you mean by "healthier diet"? Instead, "Does eating at least 5 servings per day of fresh fruits and vegetables lead to fewer upper respiratory tract infections (colds)?" is clearer and more concrete. -1 reasoning

Comment: The question is very unclear, and is buried in the intro of the dataset. It is important to be clear and specific. Add a paragraph, clearly state the question (number them if there are multiple), and give any necessary details in another paragraph. Bold the question if necessary. It is very crucial to understand the question, before moving to the EDA and methodology, as otherwise, it would be impossible to follow the project information flow.

Response:
- We got deducted for 3 point for not stating a prediction or statistical question with unclear question. But we did state that we want to  a regression problem between features of buildings to its heating and cooling load. Also we provided some methods we will use such as Linear regression, SVM and so on, also even stated the metric that we are looking for.

In this project, we attempt to find important parameters of building that affect to the heating and cooling load.
We plan to build a number of different regression models such as 
- Linear regression (Ridge, Lasso)
- Support vector machine
- Decision tree
- Xgboost
- etc ..
to predict heating and cooling load.
We then aim to find the relationship or contribution of each important features to the response
by extracting model's coefficients, feature importance, or using other explanatory methods
such as Local-interpretable-model-agnostic-explanations(LIME).


Q4.2
- The clarity of README could be improved through additional proofreading (i.e., spelling and grammatical errors are present). -1
- The proposed methodology in the README should be clearly explained, mentioning the statistical methods/models they will use (at least at a high level). -3 reasoning
Comment: I suggest adding some details on the methodology and proposed algorithms you would be using. Supervised learning is not detailed enough. Provide more details and a few sentences justifying the choices. (e.g. Ridge or other GLMs given high/low correlation of the features, collinearity, etc.)

Response:
- The README could be improved the proofreading, we agree on that one and we stated improving it in milestone2. But for this point, it stated in the milestone expectation that, the grammar error could be occur with less than 10%, and our readme file got some error but we think that it is less than 10%, and we can still understand the main idea of project proposal and what we are going to do in the project.
- We got deducted 3 points for unclear explain the methodology. We did explain the step we want to do, we are not sure what is unclear to you. We explained that we want to do regression problem of all building features related to its heating and cooling load, also proposed some model we want to use, specified the metric we are interested, and the method to do model explanation too. Could you reconsider it please.

**Comment by Suraporn** [comment]
Q6 Expectations
- GitHub issues were not used. -5
Comment: Given that GitHub issues are the best way to communicate and document the progress of the project, report the problems of the code, etc. I highly suggest that you start using them.
Response: Yes, we agree that we did not Use GitHub issue but it is because we did not know that we need to use it. In Lab, Florencia did not mention that we need to use it, she just mentioned that we can state in contributing file that if someone wants contribute, open an issue and wait for approval to work. But we did notice now that it is in expectation too, so we agree that we should got deducted but should not it too much, you deducted for 5 points, we think that 1-2 points should be more reasonable. Could you reconsider it please, Thank you. @danielramandi

**Comment by MNBhat** [comment]
Hey @danielramandi , 
Thank you for your feedback. But I have some questions hope that you can clarify 
Q2. Code of Conduct.md
 A procedure for reporting and dealing with unacceptable behavior is explicitly included.
 In particular, is important to add who to contact in case something happens. -2
Comment: This is an important section and I highly suggest adding it to your CofC.
Reponse: We appreciate the feedback. However, we have a enforcement section with just missing email ids
for the communication. Is the deduction just for the missing id's over here?

**Comment by Suraporn** [comment]
Already discussed with Daniel, issue solved. Closed.

**Comment by Suraporn** [comment]
Already discussed with Daniel, issue solved. Closed.
