### ISSUE TITLE
Milestone 2 Comments

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/energy_efficiency_analysis#93]
Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

#### 1.1 Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).
Good Job!

#### 1.2 Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [x] #126

- [x] There are not figure captions. **-2** **viz**
**Comments:** Missing figure caption in energy_report_rmd

### 1.3 Code is abstracted to functions with good function design
- [x] There are cases of functions that are too big and could be improved by defining utility functions. **-1** **reasoning**
**Comments:** The main() function in model_predict.py is quite large. I would suggest splitting it into several utility functions 

- [x] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **-1** **mechanics**
  **Comments:** Make sure to check for inputs using try-catch block (ie return error message if file does not exist when importing file)
   
### 1.4 Functions are well documented
Good Job!

 
#### 1.5 Code is called in the analysis

Good Job!
---

##### From these 7 points remove points if:

- [ ] There are cases of functions with tests that fail. **-3** **accuracy**

- [ ] There is no documentation. It is not clear what the tests are testing. **-3** **quality**

- [ ] There is commented out code. **-1** **quality**
**Comment:** No tests were included
---

#### 1.9 Dependencies have been updated (so it include the test libraries)
Good job!

#### 2.1 GitHub Issues
Good Job!

#### 2.2 Follows GitHub flow version control workflow
Good Job!

### 3.1 Analysis can be run reproducibly using documentation provided in the README
- [x] Could not reproducibly run the analysis because the code fails. **-5** **accuracy**
**Comments:** Has issues creating conda enviornment using command in usage. Also ran into an error when trying to save files using  dfi.export. 

### 4. Submission expectations

- [x] Please provide the link to the release as `https://github.com/UBC-MDS/REPOSITORY/tree/VERSION` (replacing `REPOSITORY` and `VERSION` with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. **-3** **mechanics**

**Comment by Suraporn** [comment]
Hi Glenn @Glenn032787 ,

First of all, thank you for your feedback, but we would like to clarify on some feedbacks as below,

Q1. The proposal.md file has been created and moved to the doc directory -2 mechanics #126
**_Response:_** I do not think we have the proposal.md file in doc directory, we proposed the project in proposal section in README.md
 Q2: There are not figure captions. -2 viz Comments: Missing figure caption in energy_report_rmd
**_Response:_** Which chart do you refer to? Because I think we have title for many charts and some charts we put title or explanation above or below it.

Q3: There is commented out code. -1 quality
**_Response:_** What code so we comment out? Mostly we have it as help in the first section of the code, and there are some one-line comment to note whether what that code section is for.

Q4: Could not reproducibly run the analysis because the code fails. -5 accuracy
**_Comments:_** Has issues creating conda enviornment using command in usage. Also ran into an error when trying to save files using dfi.export.
Response: We did check that the code ran fine in our environment before submitting the milestone (with Mac M1), are you sure that there is nothing wrong with your laptop ?

Q5:  Please provide the link to the release as https://github.com/UBC-MDS/REPOSITORY/tree/VERSION (replacing REPOSITORY and VERSION with the correct ones for your project version for each milestone). This makes is a lot easier for someone to just visit the repository as it was at that point in the project's history. -3 mechanics
**_Response:_** Yes, we can improve that in milestone3&4, but at least in milestone1&2, there is no specific format stated in expectation, therefor, we think that it should not be deducted.

If you have any questions, feel free to reach us all, we are welcome to provide you more explanation. Thank you and hope you reconsider this.

**Comment by Glenn032787** [comment]
Q1) In the instructions, it asks you to archive the proposal (README.md in milestone 1) to propoosal.md file in doc just to have an archive. Since you included the proposal in the README, Ill give you the mark but it is still good to archive the README from milestone 1 as proposal.md

Q2) The figures under "Exploratory data analysis with the train set" in energy_report_rmd.html does not have captions. Also none of the figures has figure numbers. For several of the figures, you just included a graph with no description or explanation of what you are trying to show. It is good that you mention how you generated the image but as this is a report, you should explain the figure and what the audience should get out of the image.

Q3) The criteria is part of the challenging question (test cases). As you did not include any test cases at all, you did not get any of the 7 marks. 

Q4) I have tried recreating the conda environment again and it resulted in ResolvePackageNotFound error. I would suggest trying to install the conda environment from scratch as that is the part that is getting the error. The purpose of this course is to have your workflows be reproducible so the environment and commands you provided should work for other computers. However, as part of milestone 4, all the dependencies should be within a docker container so you won't need to fix this for milestone 4. 

Q5) This is the standard practice to share your tagged repository as it allows people to view the repository at that tag. As the penalty was -1 for milestone 1, I will reduce to that.

Please let me know if you have any other questions.

**Comment by Suraporn** [comment]
Already discussed with Glen, issue solved. Closed.
